"""
logic/narrative_gen.py — Executive Narrative Engine
Session 02: Executive Narrative Engine

Loads flagged expense data from Session 01, connects to Gemini 2.0 Flash,
and generates a Board-level Audit Memo saved to data/executive_memo.md.
"""

import os
import sys
from pathlib import Path

import pandas as pd
from google import genai
from google.genai import types


# ── Config ────────────────────────────────────────────────────────────────────

GEMINI_MODEL = "gemini-2.5-flash"

BASE_DIR      = Path(__file__).resolve().parent.parent          # 02_executive_narrative_engine/
PROJECT_ROOT  = BASE_DIR.parent                                  # Ai Bootcamps/

INPUT_CSV     = PROJECT_ROOT / "01_data_pipeline_automation" / "data" / "flagged_expenses.csv"
OUTPUT_MD     = BASE_DIR / "data" / "executive_memo.md"


# ── Prompts ───────────────────────────────────────────────────────────────────

SYSTEM_PROMPT = (
    "You are a Senior Corporate Auditor. Your job is to transform raw flagged "
    "transaction lists into an Executive Briefing. You must identify specific "
    "systemic risks (e.g., 'Procurement Bypass' or 'Policy Ambiguity') rather "
    "than just listing transactions."
)

USER_PROMPT_TEMPLATE = (
    "Analyze these flagged items:\n\n"
    "{csv_data}\n\n"
    "Provide a 3-paragraph Board Memo in Markdown format. "
    "Each paragraph must have a bold heading. Structure: "
    "**Executive Summary**, **Systemic Risk Analysis**, **Recommended Actions**."
)


# ── Helpers ───────────────────────────────────────────────────────────────────

def load_flagged_csv(path: Path) -> str:
    """Load flagged_expenses.csv and return it as a CSV string for the LLM."""
    if not path.exists():
        raise FileNotFoundError(
            f"Flagged expenses CSV not found at:\n  {path}\n"
            "Run Session 01's cleaner.py first to generate it."
        )
    df = pd.read_csv(path)
    return df.to_csv(index=False)


def build_client() -> genai.Client:
    """Initialise the Gemini client from GEMINI_API_KEY env var."""
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise EnvironmentError(
            "GEMINI_API_KEY environment variable is not set.\n"
            "Export it with:  export GEMINI_API_KEY='your-key-here'"
        )
    return genai.Client(api_key=api_key)


def generate_memo(client: genai.Client, csv_data: str) -> str:
    """Send flagged data to Gemini and return the Board Memo text."""
    user_prompt = USER_PROMPT_TEMPLATE.format(csv_data=csv_data)
    response = client.models.generate_content(
        model=GEMINI_MODEL,
        contents=user_prompt,
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT,
        ),
    )
    return response.text


def save_memo(content: str, path: Path) -> None:
    """Write the generated memo to a Markdown file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "<!-- Executive Memo — Auto-generated by narrative_gen.py -->\n"
        "<!-- Session 02: Executive Narrative Engine -->\n\n"
    )
    path.write_text(header + content, encoding="utf-8")


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    print(f"\n{'═'*60}")
    print("  SESSION 02 — Executive Narrative Engine")
    print(f"{'═'*60}\n")

    # ── Step 1: Load flagged data ──
    try:
        print(f"[INFO]  Loading flagged data → {INPUT_CSV}")
        csv_data = load_flagged_csv(INPUT_CSV)
        row_count = csv_data.count("\n") - 1
        print(f"[INFO]  {row_count} flagged transactions loaded.")
    except FileNotFoundError as exc:
        print(f"[ERROR] {exc}")
        sys.exit(1)

    # ── Step 2: Connect to Gemini ──
    try:
        print(f"[INFO]  Connecting to {GEMINI_MODEL}...")
        client = build_client()
        print("[INFO]  Gemini client ready.")
    except EnvironmentError as exc:
        print(f"[ERROR] {exc}")
        sys.exit(1)

    # ── Step 3: Generate Board Memo ──
    try:
        print("[INFO]  Generating Executive Board Memo...")
        memo = generate_memo(client, csv_data)
        print("[INFO]  Memo generated successfully.")
    except Exception as exc:
        print(f"[ERROR] Gemini generation failed: {exc}")
        sys.exit(1)

    # ── Step 4: Save output ──
    save_memo(memo, OUTPUT_MD)
    print(f"[INFO]  Memo saved → {OUTPUT_MD}")

    print(f"\n{'═'*60}")
    print("  BOARD MEMO PREVIEW")
    print(f"{'═'*60}\n")
    print(memo)


if __name__ == "__main__":
    main()
